//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sa3adaty.DAL.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public Category()
        {
            this.ArticleCategories = new HashSet<ArticleCategory>();
            this.CategoryImages = new HashSet<CategoryImage>();
        }
    
        public int CategoryId { get; set; }
        public string Name { get; set; }
        public Nullable<int> ParentCategoryId { get; set; }
        public bool IsPublished { get; set; }
        public System.DateTime AddDate { get; set; }
        public string MetaTitle { get; set; }
        public string MetaDescription { get; set; }
        public string URL { get; set; }
        public Nullable<int> FeatureOrder { get; set; }
    
        public virtual ICollection<ArticleCategory> ArticleCategories { get; set; }
        public virtual ICollection<CategoryImage> CategoryImages { get; set; }
    }
}
