//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sa3adaty.DAL.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public Comment()
        {
            this.Comment1 = new HashSet<Comment>();
        }
    
        public int CommentId { get; set; }
        public int UserID { get; set; }
        public int ArticleId { get; set; }
        public string Text { get; set; }
        public System.DateTime AddDate { get; set; }
        public Nullable<int> ParentId { get; set; }
    
        public virtual Article Article { get; set; }
        public virtual ICollection<Comment> Comment1 { get; set; }
        public virtual Comment Comment2 { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}
