//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sa3adaty.DAL.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Image
    {
        public Image()
        {
            this.ArticleImages = new HashSet<ArticleImage>();
            this.CategoryImages = new HashSet<CategoryImage>();
            this.UserImages = new HashSet<UserImage>();
            this.AuthorImages = new HashSet<AuthorImage>();
            this.VideoImages = new HashSet<VideoImage>();
            this.VideoCategories = new HashSet<VideoCategory>();
        }
    
        public int ImageId { get; set; }
        public string URL { get; set; }
        public System.DateTime AddDate { get; set; }
        public string Caption { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<ArticleImage> ArticleImages { get; set; }
        public virtual ICollection<CategoryImage> CategoryImages { get; set; }
        public virtual ICollection<UserImage> UserImages { get; set; }
        public virtual ICollection<AuthorImage> AuthorImages { get; set; }
        public virtual ICollection<VideoImage> VideoImages { get; set; }
        public virtual ICollection<VideoCategory> VideoCategories { get; set; }
    }
}
