//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sa3adaty.DAL.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Poll
    {
        public Poll()
        {
            this.PollAnswers = new HashSet<PollAnswer>();
        }
    
        public int PollId { get; set; }
        public int Type { get; set; }
        public int CampaignId { get; set; }
        public bool IsPublished { get; set; }
        public System.DateTime AddedDate { get; set; }
        public string Question { get; set; }
        public string ImageURL { get; set; }
        public string Description { get; set; }
        public System.DateTime OnlineStartDate { get; set; }
        public System.DateTime OnlineEndDate { get; set; }
    
        public virtual Campaign Campaign { get; set; }
        public virtual ICollection<PollAnswer> PollAnswers { get; set; }
    }
}
