//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sa3adaty.DAL.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PollUserAnswer
    {
        public int UserPollAnswerID { get; set; }
        public int PollAnswerId { get; set; }
        public System.DateTime AnswerDate { get; set; }
    
        public virtual PollAnswer PollAnswer { get; set; }
    }
}
