//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sa3adaty.DAL.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PollAnswer
    {
        public PollAnswer()
        {
            this.PollUserAnswers = new HashSet<PollUserAnswer>();
        }
    
        public int AnswerId { get; set; }
        public int PollId { get; set; }
        public bool IsCorrect { get; set; }
        public string Answer { get; set; }
    
        public virtual ICollection<PollUserAnswer> PollUserAnswers { get; set; }
        public virtual Poll Poll { get; set; }
    }
}
