//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sa3adaty.DAL.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tag
    {
        public int TagId { get; set; }
        public string TagName { get; set; }
        public string MetaTitle { get; set; }
        public string MetaDescription { get; set; }
        public string FrontTitle { get; set; }
        public string FrontDescription { get; set; }
    }
}
