//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sa3adaty.DAL.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfile
    {
        public UserProfile()
        {
            this.Comments = new HashSet<Comment>();
            this.Likes = new HashSet<Like>();
            this.Subscriptions = new HashSet<Subscription>();
            this.UserImages = new HashSet<UserImage>();
            this.VideoComments = new HashSet<VideoComment>();
            this.webpages_Roles = new HashSet<webpages_Roles>();
            this.Authors = new HashSet<Author>();
        }
    
        public int UserId { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<bool> Gender { get; set; }
        public System.DateTime RegistrationDate { get; set; }
        public Nullable<int> CountryId { get; set; }
        public bool IsApproved { get; set; }
        public bool IsLockedOut { get; set; }
        public System.DateTime LastLoginDate { get; set; }
        public System.DateTime LastPasswordChangedDate { get; set; }
        public System.DateTime LastLockoutDate { get; set; }
        public Nullable<int> FailedPasswordAttemptCount { get; set; }
        public Nullable<int> FailedPasswordAnswerAttempt { get; set; }
        public string Slug { get; set; }
        public string comment { get; set; }
        public string signature { get; set; }
        public Nullable<int> Age { get; set; }
        public string Location { get; set; }
        public string Website { get; set; }
        public string Twitter { get; set; }
        public string Facebook { get; set; }
        public string Avatar { get; set; }
        public string FacebookAccessToken { get; set; }
        public Nullable<long> FacebookId { get; set; }
        public string TwitterAccessToken { get; set; }
        public string TwitterId { get; set; }
        public string GoogleAccessToken { get; set; }
        public string GoogleId { get; set; }
        public Nullable<bool> IsExternalAccount { get; set; }
        public Nullable<bool> TwitterShowFeed { get; set; }
        public Nullable<bool> DisableEmailNotifications { get; set; }
        public Nullable<bool> DisablePosting { get; set; }
        public Nullable<bool> DisablePrivateMessages { get; set; }
        public Nullable<bool> DisableFileUploads { get; set; }
        public Nullable<System.DateTime> LoginIdExpires { get; set; }
        public string MiscAccessToken { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public Nullable<System.DateTime> LastActivityDate { get; set; }
        public string Password { get; set; }
        public string PasswordSalt { get; set; }
        public string PasswordQuestion { get; set; }
        public string PasswordAnswer { get; set; }
    
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual Country Country { get; set; }
        public virtual ICollection<Like> Likes { get; set; }
        public virtual ICollection<Subscription> Subscriptions { get; set; }
        public virtual ICollection<UserImage> UserImages { get; set; }
        public virtual ICollection<VideoComment> VideoComments { get; set; }
        public virtual ICollection<webpages_Roles> webpages_Roles { get; set; }
        public virtual ICollection<Author> Authors { get; set; }
    }
}
