//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sa3adaty.DAL.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class VideoComment
    {
        public VideoComment()
        {
            this.VideoComment1 = new HashSet<VideoComment>();
        }
    
        public int CommentId { get; set; }
        public int UserId { get; set; }
        public int VideoId { get; set; }
        public string Text { get; set; }
        public System.DateTime AddDate { get; set; }
        public Nullable<int> ParentId { get; set; }
    
        public virtual Video Video { get; set; }
        public virtual ICollection<VideoComment> VideoComment1 { get; set; }
        public virtual VideoComment VideoComment2 { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}
